### ISSUE TITLE
Unique constraints are not validated by clean

### ISSUE THREAD

**Issue by tartieret** [makinacorpus/django-safedelete#203]
## Context

As mentioned in the documentation (https://django-safedelete.readthedocs.io/en/latest/models.html#fields-uniqueness), if we need to define a field uniqueness for non-deleted objects, we have to define a custom constraint such as:

```python
class Product(SafeDeleteModel):

    name = models.CharField(
        max_length=100, verbose_name=_("name"), help_text=_("Name of the product")
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["name"],
                condition=Q(deleted=None),
                name="product_unique_if_not_deleted",
            )
        ]

```

However, since we have to add a "condition" on the constraint, `Product.has_unique_fields` returns False and uniqueness validation is not performed when calling the model `.clean` method. This means that any model implementing this strategy has to implement custom validation for it

## Root cause

The django model `has_unique_fields` and `_perform_unique_checks` are overwritten in `models.SafeDeleteModel`, but they exclude unique constraints with conditions, as shown below:

![image](https://user-images.githubusercontent.com/15146307/162326830-1a7d7b67-c351-441b-8c91-26bad2ee8d16.png)

## Solution

A potential solution is to modify the overwritten `has_unique_fields` and `_perform_unique_checks`. I am happy to submit a PR for these changes, but what do you think of this change @Gagaro @AndreasBackx @palkeo  ?

**Comment by Gagaro** [comment]
We should (hopefully) have that fixed with Django 4.1 (cf https://github.com/django/django/pull/14625).

With this change, we'll have to refactor a bit what we are doing in safedelete to make it all work.

**Comment by tartieret** [comment]
Looks like you are on top of it ! :smile: 
It makes sense to solve this in Django itself. Please let me know if you need help with the changes to `django-safedelete`, we use it at work and could allocate some time to it if needed

**Comment by cosmoscalibur** [comment]
What is the status of this issue? 
We have safedelete 1.3.1 with django 4.1, but this issue still appear. So, when apply `update_or_create`, previous instance survive

**Comment by cosmoscalibur** [comment]
What is the status of this issue?
We have safedelete 1.3.1 with django 4.1, but this issue still appear. So, when apply update_or_create, previous instance survive
